name: MarryPlugin
version: 1.0-SNAPSHOT
main: me.gnarzy.marryplugin.MarryPlugin
api-version: 1.13
authors: [Gnarzy]
description: Marriage Plugin for minecrafters.
commands:
  marry:
    description: Marry a player in Minecraft.